//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMailBYEAGetMailDesktopAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebmailMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebmailMessages()
        {
            this.WebMailAttachments = new HashSet<WebMailAttachments>();
        }
    
        public long WebmailMessagesID { get; set; }
        public string FromEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string FromName { get; set; }
        public string ToEmail { get; set; }
        public System.DateTime ReceviedDate { get; set; }
        public string UIDS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebMailAttachments> WebMailAttachments { get; set; }
    }
}
