//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMailBYEAGetMailDesktopAPP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GetMailEntities : DbContext
    {
        public GetMailEntities()
            : base("name=GetMailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WebMailAttachments> WebMailAttachments { get; set; }
        public virtual DbSet<WebmailMessages> WebmailMessages { get; set; }
        public virtual DbSet<WebMailSettings> WebMailSettings { get; set; }
    }
}
