//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMailBYEAGetMailDesktopAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMailSettings
    {
        public long WebMailSettingsID { get; set; }
        public string KeyCode { get; set; }
        public string KeyValue { get; set; }
        public long KeyID { get; set; }
    }
}
