//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMailBYEAGetMailDesktopAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMailAttachments
    {
        public long AttachmentsID { get; set; }
        public byte[] Attachments_Data { get; set; }
        public string Attachments_MIME { get; set; }
        public string Attachments_Extension { get; set; }
        public string Attachments_FileName { get; set; }
        public long WebMailInfoMessageID { get; set; }
    
        public virtual WebmailMessages WebmailMessages { get; set; }
    }
}
